name: Enforce Branch Naming Convention

on: push

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Branch Name
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/heads/(feature|bugfix|hotfix)/[0-9]+-[a-zA-Z0-9_-]+$ ]]; then
            echo "ERROR: Your branch name does not follow the naming conventions!"
            echo "Branch names should follow this pattern: feature|bugfix|hotfix/issue_number-description"
            exit 1
          fi
